### ISSUE TITLE
Toggle for "RPM" unit in Fan Speed option

### ISSUE THREAD

**Issue by edilsonborges** [Moneypulation/iGlance#14]
**Hi, guys!**
First of all thank you for iGlance, it's a must have app for me.

Since the last update (**1.2.2**) I've notice that the fan speed now comes with **"RPM"** unit indicator.
A suggestion would be creating a toggle for this. In some cases, this extra space could be a benefit (e.g. I'm also using it in a 11" MacBook Air and the menu bar is smaller).

Ps: any other way to follow your work, such as twitter?

**Comment by edilsonborges** [comment]
I've created this suggestion in PR #15

**Comment by D0miH** [comment]
Great idea! PR is merged and the feature is going to be release in the next update:)
