### ISSUE TITLE
Temperature was -1°C

### ISSUE THREAD

**Issue by CoelWu** [Moneypulation/iGlance#7]
**Describe the bug**
The Temperature of CPU is -1°C，30°F

**To Reproduce**

**Expected behavior**
A Normal temperature instead of -1°C
**Screenshots**

![image](https://user-images.githubusercontent.com/39617891/46207886-752b1c80-c35b-11e8-831b-7dba40c7afdf.png)

**Desktop (please complete the following information):**
 - Mac OS 10.13.6
 - Browser safari,chrome
 - Version I complie it by myself

**Additional context**

**Comment by gieljnssns** [comment]
<img width="85" alt="schermafbeelding 2018-10-08 om 11 53 24" src="https://user-images.githubusercontent.com/17234951/46602530-c7ed9c80-caf0-11e8-847f-fa271f45df84.png">

**Comment by Moneypulation** [comment]
@gieljnssns @CoelWu do you still have this problem? If yes, @gieljnssns what is your os version and are those temperature numbers you're both getting stuck or do they vary, or even display the real temperature every now and then?

**Comment by CoelWu** [comment]
If the CPU temperature is not too high, it will be like -1°C,If it was high, for example running Xcode, it will display the right temperature.The problem happened in 10.13.6 and 10.14 Mojave

**Comment by D0miH** [comment]
Since this seems to be a bug in SMCKit I close this issue.
